language: python
python:
  - "3.2"
  - "3.3"
install:
  - pip install colorama
  - pip install coverage
  - pip install python-coveralls
  - pip install . --use-mirrors
script:
  - nosetests --with-coverage --cover-package=td
after_success:
  - coveralls
