language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - pip install coverage
  - pip install coveralls
  - pip install . --use-mirrors
script:
  - coverage run --source=td setup.py -q nosetests
  - coverage report -m
after_script:
  - coveralls --verbose
